version: '3'
services:
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env

  # postgres:
  #   image: postgres
  #   volumes:
  #     - postgres-db:/var/lib/postgresql/data


# volumes:
#   postgres-db: